### ISSUE TITLE
Feature request : Brightness control via WMI for laptop displays

### ISSUE THREAD

**Issue by rp1231** [Jaggernaut555/midi-mixer-brightness#1]
Hi Jaggernaut555,

It would be great to have brightness control via WMI for laptop displays or
for displays that do not support DDC/CI.

Thanks

**Comment by Jaggernaut555** [comment]
I've put together a pre-release of the plug in [here](https://github.com/Jaggernaut555/midi-mixer-brightness/releases/tag/v1.1.0-alpha.1) that may work for wmi control of monitor brightness.

However, I do not have a laptop or any valid monitors available to test it with.

**Comment by rp1231** [comment]
Hi @Jaggernaut555,
Thanks for putting together the pre-release.
But the laptop screen is not being detected in my case.

I use a laptop with an attached external screen,
and the external monitor(DDC/CI) is detected just fine.

Thanks

**Comment by Jaggernaut555** [comment]
Hmm. I think the external one being detected as not modifiable might be what's messing it up. I'm trying to see if I can borrow a device or something to properly test it but it might take some time.

If you can try with no external monitor plugged in, does an assignment that ends with `WMI` show up?

**Comment by rp1231** [comment]
Sure,
I'll try that out.

**Comment by rp1231** [comment]
Also, I'm not sure what you meant by 

> external one being detected as not modifiable 

Were you referring to the brightness?
Because I'm able to modify the brightness just fine......
(On the external monitor)

**Comment by rp1231** [comment]
I tried it out without the external monitor,
But it still didn't get detected.

**Comment by Jaggernaut555** [comment]
> Also, I'm not sure what you meant by
> 
> > external one being detected as not modifiable
> 
> Were you referring to the brightness? Because I'm able to modify the brightness just fine...... (On the external monitor)

I was referring the the monitor possibly not being adjustable by WMI. Alright I'll get back to this when I have a device I'm able to test on.

**Comment by Jaggernaut555** [comment]
I've got another pre-release build that can be tried, [available here](https://github.com/Jaggernaut555/midi-mixer-brightness/releases/tag/v1.1.0-alpha.2).

**Comment by rp1231** [comment]
Great!
I'll try it out!

**Comment by rp1231** [comment]
Nope, no luck with this either.....

**Comment by Jaggernaut555** [comment]
One more [new build here](https://github.com/Jaggernaut555/midi-mixer-brightness/releases/tag/v1.1.0-alpha.3). Hopefully this one works.

If it does not can you run it by clicking the `Dev mode: Disabled` button? That makes a console come up that shows some debug output.

**Comment by rp1231** [comment]
This build managed to detect the laptop screen for the first time,
But the brightness control doesn't work for the wmi monitor and it broke the brightness control for the ddc/ci enabled external monitor as well.
(The external monitor works fine if it's the only monitor in the group, but breaks if I add the laptop monitor to the group even once)

Here is the error from the Dev mode console:

DISPLAY\NCP005E\5&3a4c8c55&0&UID512_0 NCP005E UID512 WMI 60
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/lib/index.js.map: Unexpected end of JSON input
VM127 index.js:166 Error: Command failed: wmic /NAMESPACE:\\root\wmi PATH WmiMonitorBrightnessMethods WHERE "Active=TRUE AND InstanceName='DISPLAY\\NCP005E\\5&3a4c8c55&0&UID512_0'" CALL WmiSetBrightness Brightness=1 Timeout=0
The current directory is invalid.

    at ChildProcess.exithandler (VM96 node:child_process:406)
    at ChildProcess.emit (VM13 node:events:394)
    at maybeClose (VM97 child_process:1064)
    at Socket.<anonymous> (VM97 child_process:450)
    at Socket.emit (VM13 node:events:394)
    at Pipe.<anonymous> (VM98 node:net:672)
    at Pipe.callbackTrampoline (VM24 async_hooks:130)
VM127 index.js:167 Uncaught Error: Command failed: wmic /NAMESPACE:\\root\wmi PATH WmiMonitorBrightnessMethods WHERE "Active=TRUE AND InstanceName='DISPLAY\\NCP005E\\5&3a4c8c55&0&UID512_0'" CALL WmiSetBrightness Brightness=1 Timeout=0
The current directory is invalid.

    at ChildProcess.exithandler (VM96 node:child_process:406)
    at ChildProcess.emit (VM13 node:events:394)
    at maybeClose (VM97 child_process:1064)
    at Socket.<anonymous> (VM97 child_process:450)
    at Socket.emit (VM13 node:events:394)
    at Pipe.<anonymous> (VM98 node:net:672)
    at Pipe.callbackTrampoline (VM24 async_hooks:130)

**Comment by Jaggernaut555** [comment]
Alright, I think this is closer than ever now with this [new pre-release build](https://github.com/Jaggernaut555/midi-mixer-brightness/releases/tag/v1.1.0-alpha.4).

**Comment by rp1231** [comment]
It stopped detecting the laptop display again in the new build.

I use a brightness control software that's written in javascript that uses this:
https://github.com/djsweet/win32-displayconfig
Maybe this can be useful?
I'm not a coder so I don't know.....
Both my screens are detected by that software.
If you want I can paste a link to that software here.

**Comment by Jaggernaut555** [comment]
I very briefly had my hands on a laptop and found out why that last build didn't show the device. I have [another build here](https://github.com/Jaggernaut555/midi-mixer-brightness/releases/tag/v1.1.0-alpha.5).

**Comment by rp1231** [comment]
This one worked!
I can only imagine how annoying it must be to write code without a device to test on.....

But came across another bug unfortunately.

The plugin works fine if the group only has either one of the monitors.
But if I add both, the wmi and ddc/ci monitors to a single group and turn the knob,
the brightness functionality for the wmi monitor breaks.
The ddc/ci monitor keeps on working fine though.

Thanks

**Comment by Jaggernaut555** [comment]
Does anything show up in the console if you enable dev mode? This behaviour seems strange to me cause nothing about assigning both at once should impact each other.

If you're starting with both monitors at different brightness levels the behaviour might feel weird cause they'll jump from where ever they were to the new level. Even if they were at significantly different levels to begin with.

**Comment by rp1231** [comment]
Nope, it just breaks.....
The controls are working great though if I assign the monitors to different knobs.

This is the output from the console:
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/lib/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/lib/ddcci.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/lib/util.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/lib/wmi.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/node-powershell/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/child-shell/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/child-shell/dist/errors.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/child-shell/dist/converters.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/child-shell/dist/Shell.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/accumulate-stream/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut…xer.brightness/node_modules/accumulate-stream/dist/AccumulateStream.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/trim-buffer/dist/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/rajpa/AppData/Roaming/midi-mixer-app/plugins/ca.jaggernaut.midi-mixer.brightness/node_modules/node-powershell/dist/PowerShell.js.map: Unexpected end of JSON input
wmi.js:22 Converting single WMI monitor to array

**Comment by rp1231** [comment]
Also I noticed that when both the monitors are grouped,
The wmi monitor reacts to the first twist of the knob and stops reacting after the first twist.

**Comment by Jaggernaut555** [comment]
I'm gonna close this issue of adding WMI support and create a new issue for the grouping problem.
