### ISSUE TITLE
Bug: The plugin deactivates if you try to control a monitor that's turned off

### ISSUE THREAD

**Issue by izhekov** [Jaggernaut555/midi-mixer-brightness#4]
Having 3 monitors setup. I'm often turning off some of them. If I try to control a monitor that's currently not active, the whole plugin gets disabled.

**Comment by Jaggernaut555** [comment]
Thanks for the bug report. I've repro'd this with my own monitors and have included a fix in [version 1.1.0](https://github.com/Jaggernaut555/midi-mixer-brightness/releases/tag/v1.1.0).

**Comment by izhekov** [comment]
Hi and thanks. I just compiled the 1.1.0 version but it doesn't seems to be fixed for me.

Steps I'm following are simple:
Turn off one of the monitors.
Try to adjust the brightness of that particular monitor.

Result: The plugin becomes in unloaded state, and needs to be manually reactivated.

**Comment by Jaggernaut555** [comment]
Yeah, that's the exact thing I found with the previous version. Can you double check that the new version installed correctly?

Click the "folder" button under the plugin activation and check the plugin.json file that it is version 1.1.0

**Comment by izhekov** [comment]
Hi and thanks. Indeed it works and the issue seems to be fixed. I got it wrong as after replacing the plugin, an older version seems to be cached even that I physically deleted it.
